// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiz1RxwNH23NTFD1CZueiMkwK7kIeaVXA',
    appId: '1:213723168691:web:644d9f1a0f12ebdca555c6',
    messagingSenderId: '213723168691',
    projectId: 'justhosting-23057',
    authDomain: 'justhosting-23057.firebaseapp.com',
    storageBucket: 'justhosting-23057.firebasestorage.app',
    measurementId: 'G-KK4G1PJ2CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAShtN-gZh2jbbgJfEt5osawlqk1pNfH4w',
    appId: '1:213723168691:android:35e0bcd6b7bfd4b7a555c6',
    messagingSenderId: '213723168691',
    projectId: 'justhosting-23057',
    storageBucket: 'justhosting-23057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLmWtIzMqN7ZnkcpntNTvSjQVoOx1XlI',
    appId: '1:213723168691:ios:c1683de3aca23a6fa555c6',
    messagingSenderId: '213723168691',
    projectId: 'justhosting-23057',
    storageBucket: 'justhosting-23057.firebasestorage.app',
    iosBundleId: 'com.example.waliProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJLmWtIzMqN7ZnkcpntNTvSjQVoOx1XlI',
    appId: '1:213723168691:ios:c1683de3aca23a6fa555c6',
    messagingSenderId: '213723168691',
    projectId: 'justhosting-23057',
    storageBucket: 'justhosting-23057.firebasestorage.app',
    iosBundleId: 'com.example.waliProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiz1RxwNH23NTFD1CZueiMkwK7kIeaVXA',
    appId: '1:213723168691:web:41cf792808635a3da555c6',
    messagingSenderId: '213723168691',
    projectId: 'justhosting-23057',
    authDomain: 'justhosting-23057.firebaseapp.com',
    storageBucket: 'justhosting-23057.firebasestorage.app',
    measurementId: 'G-SGLS76ZMJL',
  );

}