// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqSz-gQc1MtZojh7AoqULv5xtVe1jp_jY',
    appId: '1:604942026658:web:b79f184b9a442abba914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    authDomain: 'realstate-3e60d.firebaseapp.com',
    storageBucket: 'realstate-3e60d.appspot.com',
    measurementId: 'G-0B0T1G8GF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGsHadYJ2UjExwkEPXcTHBqmcNDNPLIA',
    appId: '1:604942026658:android:0d3400d4de2302e2a914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIod1C8wbHyfquPCJ8fnmsDEBoHO1haNQ',
    appId: '1:604942026658:ios:d805eb0a0483ee5da914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
    iosBundleId: 'com.example.waliProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIod1C8wbHyfquPCJ8fnmsDEBoHO1haNQ',
    appId: '1:604942026658:ios:d805eb0a0483ee5da914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
    iosBundleId: 'com.example.waliProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDncU_IRj3lAO7ICgpwS0vOh-oL8d7Js3U',
    appId: '1:604942026658:web:8d31faa47c8ed36ca914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    authDomain: 'realstate-3e60d.firebaseapp.com',
    storageBucket: 'realstate-3e60d.appspot.com',
    measurementId: 'G-M4XKQWQJ8Y',
  );

}